a: *.h *.cpp
	g++ *.cpp -o main

comp:
	g++ *.cpp -o main
	
comprun:
	g++ *.cpp -o main
	./main 5 257270 20

run:
	./main 5 257270 20
	
clean:
	rm *.o main

tar: 
	tar -cvz *.h *.cpp makefile -f Upload.tar